### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Klng79** [amir9480/vscode-laravel-extra-intellisense#7] opened 2019-04-06 03:34 UTC
- Issue Type: `Performance`
- Extension Name: `laravel-extra-intellisense`
- Extension Version: `0.1.3`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/alexng/amiralizadeh9480.laravel-extra-intellisense-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by amir9480** [comment] 2019-04-06 07:22
duplicate of #4

**Closed by amir9480** 2019-04-06 07:22 UTC
