### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by itguy614** [amir9480/vscode-laravel-extra-intellisense#6] opened 2019-04-05 15:54 UTC
- Issue Type: `Performance`
- Extension Name: `laravel-extra-intellisense`
- Extension Version: `0.1.3`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.0`

[amiralizadeh9480.laravel-extra-intellisense-unresponsive.cpuprofile.txt](https://github.com/amir9480/vscode-laravel-extra-intellisense/files/3048716/amiralizadeh9480.laravel-extra-intellisense-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by itguy614** [comment] 2019-04-05 15:55
Not really a dupe.  Second platform.  This started occurring after the latest VSCode update.

**Comment by itguy614** [comment] 2019-04-05 16:05
Removing extension and reinstalling seems to have helped my situation.

**Comment by amir9480** [comment] 2019-04-05 19:51
I using regex to parse function calls.
This happens  just for special part of codes that causes infinite loop.

Function regex:
```regex
/((([A-Za-z0-9_]+)::)?([@A-Za-z0-9_]+)\()((?:[^)(]+|\((?:[^)(]+|\([^)(]*\))*\))*)(\)|$)/g
```

Inline functions regex:
```regex
/((\s*\,\s*)?)(\[.*\]|array\(.*\)|(\"((\\\")|[^\"])*\")|(\'((\\\')|[^\'])*\'))/g
```

And function arguments:
```regex
/\((([\s\S]*\,)?\s*function\s*\(.*\)\s*\{)([\S\s]*)\}/g
```

**Comment by amir9480** [comment] 2019-04-06 07:22
duplicate of #4

**Closed by amir9480** 2019-04-06 07:22 UTC
